# Generated by Django 2.2.6 on 2019-12-23 18:04

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('slug', autoslug.fields.AutoSlugField(always_update='True', editable=False, max_length=60, populate_from='title', unique='True')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сортировать')),
            ],
            options={
                'verbose_name': 'Галерея с фото',
                'verbose_name_plural': 'Галерии с фото',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('videoId', models.CharField(max_length=20)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сортировать')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VideoProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(max_length=100, verbose_name='Свойство')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сортировать')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Video')),
            ],
            options={
                'verbose_name': 'Свойство',
                'verbose_name_plural': 'Свойства',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='Подпись')),
                ('picture', models.ImageField(default=None, upload_to='', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.PhotoCategory')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'ordering': ['order'],
            },
        ),
    ]
