# Generated by Django 2.2.6 on 2019-12-23 18:04

import autoslug.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', autoslug.fields.AutoSlugField(always_update='True', editable=False, max_length=220, populate_from='title', unique='True')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Подзаголовок')),
                ('img_square', models.ImageField(default='blog_default_square.jpg', upload_to='', verbose_name='Квадратная картинка')),
                ('img_long', models.ImageField(default='blog_default_long.jpg', upload_to='', verbose_name='Широкая картинка')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(default="<div class='container'>      </div>", verbose_name='Текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сортировать')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['order'],
            },
        ),
    ]
