# Generated by Django 2.2.6 on 2019-12-23 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('picture', models.ImageField(default=None, upload_to='', verbose_name='Картинка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сортировать')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Ссылка')),
                ('desktop', models.ImageField(default=None, upload_to='', verbose_name='Большие экраны (от 750px)')),
                ('tablet', models.ImageField(default=None, upload_to='', verbose_name='Планшеты (от 600px до 750px)')),
                ('mobile', models.ImageField(default=None, upload_to='', verbose_name='Телефоны (до 600px)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сортировать')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('text', models.TextField(default='', max_length=260, verbose_name='Текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сортировать')),
            ],
            options={
                'verbose_name': 'Галерея с фото работ',
                'verbose_name_plural': 'Галереи с фото работ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_top', models.ImageField(default=None, upload_to='', verbose_name='Верхняя')),
                ('picture_bottom', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Нижняя')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сортировать')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.PortfolioCategory')),
            ],
            options={
                'verbose_name': 'Фото работ',
                'verbose_name_plural': 'Фото работ',
                'ordering': ['order'],
            },
        ),
    ]
