# Generated by Django 2.2.6 on 2019-12-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_firstscreenimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstscreenimg',
            name='isDark',
            field=models.BooleanField(default=False, verbose_name='Темный бургер и НАШИ РАБОТЫ'),
        ),
    ]
